#!/bin/sh

set -ue

if test -f ./*html; then
  rm ./*html
fi

for filepath in ./src/*.md; do
  filename="$(basename "$filepath")"
  title=$(grep '#' "$filepath" | head -n 1 | sed 's/# //g')
  {
    echo '<!DOCTYPE html>'
    echo '<html>'
    echo '<head>'
    echo '<meta charset="UTF-8">'
    echo "<title>$title</title>"
    echo '<link rel="stylesheet" href="styles.css">'
    echo '</head>'
    echo '<body>'
    markdown "$filepath"
    echo '</body>'
    echo '</html>'
  } >>"${filename%.*}".html
done
